### ISSUE TITLE
les xpath n'est plus valide je crois

### ISSUE THREAD

**Issue by jeanjakeunuk** [pierreminiggio/tiktok-poster#1]

**Comment by pierreminiggio** [comment]
Probable, j'ai mon upload qui ne fonctionnait plus depuis à peu près 2 mois, et j'ai pas encore eu le temps de tester si c'était car je me mangeais un Captcha ou bien si l'interface de TikTok a évolué.
Je ne vais pas avoir de temps pour débugger ça avant un moment.

**Comment by pierreminiggio** [comment]
J'ai fait une mise à jour, ça fonctionne à nouveau :D
